### ISSUE TITLE
Wiki: Forking is probably not the right way to integrate this

### ISSUE THREAD

**Issue by tuh8888** [callahantiff/Abra-Collaboratory#11] opened 2019-04-11 20:36 UTC
**Wiki Page:**
- README.md

**Suggestions:**
So far, for my use cases, I have been converting current projects to be Abra-Collaboratory complient projects. To do this, I have used the script proposed in [this pull request](https://github.com/callahantiff/Abra-Collaboratory/pull/10). This has worked pretty well for the most part. The only time consuming step is the copying of the project boards.

I think the suggested first step of the README (forking the Abra-Collaboratory repository), is not going to be the best way to start a project. Instead, users should create a new repository the standard way (clicking the + button on GitHub). Then copy over resources from Abra-Collaboratory into their project and follow the procedure starting from step 2. For users with current projects, they can skip this step.

- [ ] Change first step to create new repository instead of forking.
- [ ] Suggest users with current projects who wish to convert to the Abra-Collaboratory framework start at step 2.

**Comment by magic-lantern** [comment] 2019-04-15 20:49
I agree with @tuh8888 that the goal is to create a project compliant with the Abra-Collaboratory philosophy. The structure is what we really want; items like the README.md and LICENSE would need to be customized based on the project's needs.

I think that it would be beneficial for the new project creation script to replace the README.md with a template with instructions telling what items are recommended to go in the README.md.

I also agree that the not all the wiki pages should be carried over to a new project. Home should be updated similar the README.md, and pages like the To-Do list would need to be customized. I do however, think it important to keep the *...Reproducible...* pages as they have important information that I would want users of my project to know. Replacing the term 'PheKnowVec' with the newly created project would be a good start there rather than removing them.

To me, forking seems easier than copying everything out of the upstream Abra-Collaboratory repository, but if the process is automated, it doesn't really matter how it happens on the backend.

**Comment by callahantiff** [comment] 2019-04-28 20:36
@magic-lantern and @tuh8888 I think we have addressed everything here, thanks to the awesome contributions you both made 👏. Unless I am missing something, OK to close this?

**Comment by magic-lantern** [comment] 2019-04-29 16:21
I agree this can be closed, but since it was opened by @tuh8888, I'll let them make the final decision.

**Comment by callahantiff** [comment] 2019-04-29 16:33
Agree, @tuh8888 please close this issue if you feel it is resolved.

**Closed as completed** 2019-04-30 17:58 UTC
Labels: wiki
